### ISSUE TITLE
COLLECTION & WATCHLIST for Trakt isn't working after authenticating. 

### ISSUE THREAD

**Issue by LJHookem14** [OpenELEQ/repository.q#2]
NEXT EPISODES & CALENDAR is working but not COLLECTION and WATCHLIST

**Comment by LJHookem14** [comment]
I'm talking about MetalliQ of course. The LISTS section is working fine.

**Comment by OpenELEQ** [comment]
Just tested on fresh install and it's working as it should here. Please post future bug or error reports in the support thread on noobsandnerds forum, link to a full debug log required.
